"""not much of a notebook, but it's the only one i've got"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['factorial', 'foo']

# %% ../nbs/00_core.ipynb 2
def factorial(n):
    "compute a factorial"
    y = 1
    for i in range(1,n+1):
        y *=i
    return y


# %% ../nbs/00_core.ipynb 5
def foo(): pass
